name: Deploy to Deno

on:
  push:
    branches:
      - main

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Install Curl
      uses: sozo-design/curl@v1.0.2
      with:
        args: https://httpbin.org/get
    - name: Deploy to Deno
      run: |
        cd exhloj
        curl -fsSL https://deno.land/x/install/install.sh | sh
        ~/.deno/bin/deno install -A --no-check -r -f https://deno.land/x/deploy/deployctl.ts
        deployctl deploy --project=exhloj --prod backend/server.ts
        cd ..
      env:
        DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}