name: Deploy to Deno

on:
  push:
    branches:
      - main

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Deploy to Deno
      run: |
        cd exhloj
        npm i
        curl -fsSL https://deno.land/x/install/install.sh | sh
        export DENO_INSTALL="/home/runner/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
        deno install -A --no-check -r -f https://deno.land/x/deploy/deployctl.ts
        deployctl deploy --project=exhloj --prod backend/server.ts
        cd ..
      env:
        DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}